spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ich_platform
    username: root
    password: MYSQL123123..
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhiwenliu.feiyihouduan.pojo.vo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
server:
  port: 8081